### ISSUE TITLE
Duplication of docs in analysis & examples

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/UserGuide#237]
We are getting a lot of "duplicate label" issues when building the docs.

Took me far too long to debug, but it turns out that the issue is that we have parts of the docs that appear twice under two difference sections.

For example; https://userguide.mdanalysis.org/stable/examples/analysis/alignment_and_rms/README.html
and
https://userguide.mdanalysis.org/stable/examples/analysis/README.html#alignments-and-rms-fitting

are actually the same thing, but just in two different places.

Additionally, we have cases where we end up with pages that are accessible only under `analysis`, but are technically present under `examples`, for example: https://userguide.mdanalysis.org/stable/examples/analysis/hydrogen_bonds/hbonds.html

I realise some pages might be relevant in two different sections, but this might actually be more confusing than anything else. In my opinion, we need to work out how best to handle this and clean up accordingly.

**Comment by IAlibay** [comment]
Relevant warning messages:

```
/home/bioc1523/github/UserGuide/doc/source/examples/analysis/alignment_and_rms/README.rst:7: WARNING: duplicate label alignment-and-rms, other instance in /home/bioc1523/github/UserGuide/doc/source/examples/analysis/README.rst
/home/bioc1523/github/UserGuide/doc/source/examples/analysis/hydrogen_bonds/README.rst:7: WARNING: duplicate label hydrogen-bonds, other instance in /home/bioc1523/github/UserGuide/doc/source/examples/analysis/README.rst
/home/bioc1523/github/UserGuide/doc/source/examples/analysis/trajectory_similarity/README.rst:6: WARNING: duplicate label trajectory-similarity, other instance in /home/bioc1523/github/UserGuide/doc/source/examples/analysis/README.rst
```

**Comment by jandom** [comment]
For anybody working on this, the build can be made to error with 

```
make html SPHINXOPTS="-W --keep-going"
```

But obviously it's fixing the warnings that will take 99% of the work, not setting this flag as the default

**Comment by mhmohona** [comment]
Hello @IAlibay, may I work on this issue?

**Comment by RMeli** [comment]
@mhmohona sure, you are welcome to work on the issue. However, there is some discussion that needs to happen.

> we need to work out how best to handle this and clean up accordingly

Please discuss here your suggested solution. When there is consensus on how to address this issue, then it can be fixed accordingly.

**Comment by mhmohona** [comment]
Thank @RMeli! So initially I thought I would run commands to see the errors and then decide whats the next step seeing the output.
However, I am having problem with installing dependencies to run UserGuide. 
I am following this [guide](https://userguide.mdanalysis.org/stable/contributing_docs.html#building-the-user-guide) and while running `make html` command getting following error - 

![image](https://github.com/user-attachments/assets/74e7974b-2b03-45bd-94ee-ee548e0e2b43)

would you please share what versions you have installed in your device after running `conda env create --file environment.yml --quiet`? It would be really great if you could provide me the versions by running `conda list --export > requirements.txt`. Also which version of Python you have. 

Thanks in advance. 😀

**Comment by mhmohona** [comment]
Another thing I want to bring your attention is, I had faced lots of trouble while trying to run `conda env create --file environment.yml --quiet` command. My OS is Ubuntu and here is the error message - 

```
$ conda env create --file environment.yml --quiet
conda activate mda-user-guide
jupyter-nbextension enable nglview --py --sys-prefix
Channels:
 - jaimergp/label/unsupported-cudatoolkit-shim
 - conda-forge
 - plotly
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html




Traceback (most recent call last):
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/filters/markdown_mistune.py", line 24, in <module>
    from mistune import (  # type:ignore[attr-defined]
ImportError: cannot import name 'BlockParser' from 'mistune' (/home/mona/.local/lib/python3.10/site-packages/mistune.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/notebook/nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/notebook/nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/traitlets/utils/importstring.py", line 41, in import_item
    return __import__(parts[0])
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/latex_envs/__init__.py", line 3, in <module>
    from . import latex_envs
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/latex_envs/latex_envs.py", line 20, in <module>
    from nbconvert.exporters.exporter import Exporter
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/__init__.py", line 7, in <module>
    from .exporters import (
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/exporters/__init__.py", line 4, in <module>
    from .html import HTMLExporter
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/exporters/html.py", line 29, in <module>
    from nbconvert.filters.markdown_mistune import IPythonRenderer, MarkdownWithMath
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/filters/markdown_mistune.py", line 39, in <module>
    from mistune import (  # type: ignore[attr-defined]
ImportError: cannot import name 'PLUGINS' from 'mistune' (/home/mona/.local/lib/python3.10/site-packages/mistune.py)

Enabling: jupyter_nbextensions_configurator
- Writing config: /home/mona/miniconda/envs/mda-user-guide/etc/jupyter
    - Validating...
      jupyter_nbextensions_configurator 0.6.1 OK
Enabling notebook nbextension nbextensions_configurator/config_menu/main...
Enabling tree nbextension nbextensions_configurator/tree_tab/main...

Traceback (most recent call last):
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/filters/markdown_mistune.py", line 24, in <module>
    from mistune import (  # type:ignore[attr-defined]
ImportError: cannot import name 'BlockParser' from 'mistune' (/home/mona/.local/lib/python3.10/site-packages/mistune.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mona/miniconda/envs/mda-user-guide/bin/jupyter-contrib-nbextension", line 6, in <module>
    from jupyter_contrib_nbextensions.application import main
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/jupyter_contrib_nbextensions/application.py", line 13, in <module>
    from jupyter_contrib_nbextensions.install import (
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/jupyter_contrib_nbextensions/install.py", line 16, in <module>
    import jupyter_contrib_nbextensions.nbconvert_support
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/jupyter_contrib_nbextensions/nbconvert_support/__init__.py", line 5, in <module>
    from .collapsible_headings import ExporterCollapsibleHeadings
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/jupyter_contrib_nbextensions/nbconvert_support/collapsible_headings.py", line 10, in <module>
    from .exporter_inliner import ExporterInliner
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/jupyter_contrib_nbextensions/nbconvert_support/exporter_inliner.py", line 5, in <module>
    from nbconvert.exporters.html import HTMLExporter
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/__init__.py", line 7, in <module>
    from .exporters import (
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/exporters/__init__.py", line 4, in <module>
    from .html import HTMLExporter
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/exporters/html.py", line 29, in <module>
    from nbconvert.filters.markdown_mistune import IPythonRenderer, MarkdownWithMath
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/filters/markdown_mistune.py", line 39, in <module>
    from mistune import (  # type: ignore[attr-defined]
ImportError: cannot import name 'PLUGINS' from 'mistune' (/home/mona/.local/lib/python3.10/site-packages/mistune.py)

done
ERROR conda.core.link:_execute(950): An error occurred while installing package 'conda-forge::jupyter_latex_envs-1.4.6-pyhd8ed1ab_1002'.
Rolling back transaction: ...working... done

LinkError: post-link script failed for package conda-forge::jupyter_latex_envs-1.4.6-pyhd8ed1ab_1002
location of failed script: /home/mona/miniconda/envs/mda-user-guide/bin/.jupyter_latex_envs-post-link.sh
==> script messages <==
Traceback (most recent call last):
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/filters/markdown_mistune.py", line 24, in <module>
    from mistune import (  # type:ignore[attr-defined]
ImportError: cannot import name 'BlockParser' from 'mistune' (/home/mona/.local/lib/python3.10/site-packages/mistune.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/notebook/nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/notebook/nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/traitlets/utils/importstring.py", line 41, in import_item
    return __import__(parts[0])
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/latex_envs/__init__.py", line 3, in <module>
    from . import latex_envs
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/latex_envs/latex_envs.py", line 20, in <module>
    from nbconvert.exporters.exporter import Exporter
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/__init__.py", line 7, in <module>
    from .exporters import (
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/exporters/__init__.py", line 4, in <module>
    from .html import HTMLExporter
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/exporters/html.py", line 29, in <module>
    from nbconvert.filters.markdown_mistune import IPythonRenderer, MarkdownWithMath
  File "/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/nbconvert/filters/markdown_mistune.py", line 39, in <module>
    from mistune import (  # type: ignore[attr-defined]
ImportError: cannot import name 'PLUGINS' from 'mistune' (/home/mona/.local/lib/python3.10/site-packages/mistune.py)

==> script output <==
stdout: 
stderr: 
return code: 1

()

Command 'jupyter-nbextension' not found, but can be installed with:
sudo apt install jupyter-notebook
```
The problem didnt solved just after installing jupyter-notebook, rather after uncessful attempts, i cleaned everything, relevent side packages and then I had to run commands like this to reach to the make command - 


```
(base) mona@mhm:~/Desktop/github/MDAnalysis-UserGuide$ conda activate mda-user-guide
(mda-user-guide) mona@mhm:~/Desktop/github/MDAnalysis-UserGuide$ pip install mistune==2.0.4
Collecting mistune==2.0.4
  Downloading mistune-2.0.4-py2.py3-none-any.whl.metadata (1.5 kB)
Downloading mistune-2.0.4-py2.py3-none-any.whl (24 kB)
Installing collected packages: mistune
  Attempting uninstall: mistune
    Found existing installation: mistune 0.8.4
    Uninstalling mistune-0.8.4:
      Successfully uninstalled mistune-0.8.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
m2r2 0.3.3.post2 requires mistune==0.8.4, but you have mistune 2.0.4 which is incompatible.
Successfully installed mistune-2.0.4
```
```
(mda-user-guide) mona@mhm:~/Desktop/github/MDAnalysis-UserGuide$ conda install -c conda-forge jupyter_latex_envs
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.
```
```
(mda-user-guide) mona@mhm:~/Desktop/github/MDAnalysis-UserGuide$ jupyter-nbextension enable nglview --py --sys-prefix
Enabling notebook extension nglview-js-widgets/extension...
      - Validating: OK
(mda-user-guide) mona@mhm:~/Desktop/github/MDAnalysis-UserGuide$ cd doc/
make html
./source/scripts/generate_all.sh
/home/mona/miniconda/envs/mda-user-guide/bin/python
2.8.0-dev0
2.8.0-dev0
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/format_overview.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/coordinate_readers.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/DATA.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/IN.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/COOR.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/OPENMMAPP.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/OPENMMTOPOLOGY.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/PDB.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/CONFIG.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/CHEMFILES.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/MMTF.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/XPDB.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/RDKIT.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/ITP.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/XML.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/LAMMPSDUMP.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/OPENMMSIMULATION.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/DCD.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/GMS.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TRJ.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/DMS.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/H5MD.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/NCDF.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TPR.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/GSD.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/XYZ.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/GRO.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/LAMMPS.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TRC.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TRR.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/XTC.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TOP.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/PARMED.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TRZ.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/MOL2.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/HISTORY.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TXYZ.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/INPCRD.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/PQR.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/PSF.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/PDBQT.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/CRD.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TNG.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/selection_exporter_formats.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/selections/protein.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/selections/protein_backbone.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/selections/nucleic.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/selections/nucleic_backbone.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/selections/base.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/selections/nucleic_sugar.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/topology/groupmethods.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/topology/defaults.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/topology_parsers.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/topology/topologyattrs.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/topology/connectivityattrs.txt
Wrote  generated/units_table.txt
Running Sphinx v7.4.7
/home/mona/miniconda/envs/mda-user-guide/bin/python
2.8.0-dev0
2.8.0-dev0
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/format_overview.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/coordinate_readers.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/PSF.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/IN.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/GSD.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TPR.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TOP.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/MOL2.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/NCDF.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/OPENMMTOPOLOGY.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/XYZ.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/DMS.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/XTC.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/LAMMPS.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/GMS.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/DCD.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/HISTORY.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/OPENMMSIMULATION.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/RDKIT.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/ITP.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/DATA.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TRR.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TRZ.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/H5MD.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/MMTF.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/OPENMMAPP.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TXYZ.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/CHEMFILES.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/COOR.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/GRO.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/XPDB.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/INPCRD.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/CRD.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/PDB.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TNG.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/LAMMPSDUMP.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TRC.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/PARMED.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/XML.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/PQR.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/CONFIG.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/PDBQT.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/reference/classes/TRJ.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/selection_exporter_formats.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/selections/protein.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/selections/protein_backbone.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/selections/nucleic.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/selections/nucleic_backbone.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/selections/base.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/selections/nucleic_sugar.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/topology/groupmethods.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/topology/defaults.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/formats/topology_parsers.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/topology/topologyattrs.txt
Wrote  /home/mona/Desktop/github/MDAnalysis-UserGuide/doc/source/generated/topology/connectivityattrs.txt
Wrote  generated/units_table.txt
loading translations [en]... done

Extension error:
Could not import extension nbsphinx (exception: cannot import name 'AstRenderer' from 'mistune.renderers' (/home/mona/miniconda/envs/mda-user-guide/lib/python3.10/site-packages/mistune/renderers/__init__.py))
make: *** [Makefile:31: html] Error 2
```

**Comment by mhmohona** [comment]
@RMeli So I ran `make html SPHINXOPTS="-W --keep-going` command and got following error - 
![image](https://github.com/user-attachments/assets/b1e9fbc6-4790-4fa7-9821-bc11afa68b3c)

is addressing these errors enough to solve this issue? Or do I need to do manual review through out the document?

**Comment by mhmohona** [comment]
Hey @RMeli, I’ve compiled a detailed table outlining the current status, duplication levels, and recommended actions across MDAnalysis resources (User Guide, website, Docs, and GitHub Wiki). Please review and let me know if further adjustments are needed.

| **Page Name** | **Platforms** | **Duplication Level** | **Unique Content** | **Recommended Action** | **Role & Cross-Linking Plan** |
|---------------|---------------|-----------------------|--------------------|------------------------|-----------------------------|
| [Installation](https://userguide.mdanalysis.org/stable/installation.html) | User Guide, Main Website, Docs, GitHub | 100% | User Guide: Detailed pip/conda instructions, Docs: Technical notes | Consolidate into User Guide with quick links from website and GitHub | User Guide: Primary source, website points users to Guide; GitHub Wiki focuses on community troubleshooting for installation issues |
| [Quick Start](https://www.mdanalysis.org/pages/installation_quick_start/) | User Guide, Main Website | 80% | User Guide: Expanded examples, Website: Minimal setup steps | Keep primary content in User Guide; website provides a concise intro with link | Cross-link from website homepage and Docs to the User Guide quick start page |
| [Features](https://userguide.mdanalysis.org/stable/examples/README.html) | User Guide, Main Website | 70% | User Guide: Feature examples, Website: Overview | Retain overview on website; link detailed content to User Guide | Add section on homepage linking to User Guide’s advanced features with examples |
| [Tutorials](https://userguide.mdanalysis.org/stable/examples/README.html) | User Guide, GitHub Wiki | 60% | Wiki: Archived tutorials, User Guide: Latest tutorials | Archive older tutorials in Wiki, redirect to User Guide for updated versions | Tutorials guide users to relevant sections in Docs and FAQs for deeper exploration |
| [Troubleshooting](https://docs.mdanalysis.org/en/latest/troubleshooting.html) | Docs, GitHub Wiki | 50% | Docs: Structured troubleshooting steps, Wiki: User-generated Q&A | Keep structured troubleshooting in Docs, use Wiki for discussions | Docs link to GitHub Discussions for community solutions and follow-ups |
| [FAQ](https://github.com/MDAnalysis/mdanalysis/blob/master/docs/faq.md) | Website, GitHub Wiki, User Guide | 40% | Different questions across platforms | Merge FAQs into User Guide, cross-link from other locations | Add a “Search FAQ” option on the website linking to User Guide FAQs |
| [Privacy Policy](https://www.mdanalysis.org/privacy-policy/) | Dedicated Page | 100% | Uniform across platforms | Keep as-is with references across all platforms | Link from all main platforms to the central privacy policy page |
| [Core Objects](https://docs.mdanalysis.org/en/latest/core_objects/index.html) | Docs, User Guide | 80% | Docs: API details, User Guide: Practical usage | Keep API info in Docs, move examples to User Guide | Cross-link technical API documentation from User Guide practical examples |
| [Group Operations](https://docs.mdanalysis.org/en/latest/core_objects/group_operations.html) | Docs, User Guide | 75% | User Guide: Application-based, Docs: API-level details | Retain API documentation in Docs, practical usage in User Guide | Link User Guide examples directly to API methods in Docs |
| [Contributing](https://github.com/MDAnalysis/mdanalysis/blob/master/CONTRIBUTING.rst) | User Guide, GitHub Wiki | 50% | User Guide: Detailed process, Wiki: Short guidelines | Move full process to User Guide, leave Wiki for quick tips | Create a contribution workflow diagram with cross-links between User Guide and GitHub |
